@startuml sequenceDiagram
  participant "cmd\n:BusinessTransactionCommand" as cmd
  participant "httpSession\n:HttpSession" as hs
  participant "appSession\n:ApplicationSession" as apps
  participant "<<Singleton>>\nAppSessionManager" as sm

  activate cmd
    create hs
    cmd->>hs: httpSession =\n　　getReq().getSession(true)
    cmd->>hs: getAttribute(APP_SESSION)
    activate hs
      hs-->>cmd: Object appSessionObject
    deactivate hs
    create apps
    cmd->>apps: appSession = (ApplicationSession) appSessionObject
    cmd->>sm: setSession(appSession)
    activate sm
    deactivate sm
  deactivate cmd
@enduml