@startuml sequenceDiagram
  participant "cmd\n:Command" as cmd
  participant "lock\n:ReadWriteLockManager" as lm
  database PostgreSQL as db

  activate cmd
    cmd->>lm: releaseWriteLock(lockableID)
    activate lm
      lm->>db: DELETE FROM lock WHERE lockableid = uuid(lockableID) AND version = <WRITE>;
      activate db
      deactivate db
    deactivate lm
  deactivate cmd
@enduml