@startuml sequenceDiagram
  participant Frontend as FE
  participant "controllers/.../\nViewVenue" as cvv
  participant "cmd\n:Command" as cmd
  participant "lock\n:ReadWriteLockManager" as lm
  participant "<<Singleton>>\nUnitOfWork" as uw
  participant DBUtil
  
  ' participant "mapper\n:VenueMapper" as VM
  ' participant "plannerEvent\n:Object[]" as Sc
  ' participant "e\n:Event" as Vn
  ' participant "<color:darkRed>allEvents\n<color:darkRed>:Map<UUID, Event>" as AV

  activate FE
    FE->>cvv: doPost(request, response)
    activate cvv
      alt request.getParameter("mode") == "one"
        ref over cvv
          N/A. No use case uses this mode.
        end ref
      else request.getParameter("mode") == "all"
        create cmd
        cvv->>cmd: cmd = new ReleaseAllVenueCommand()
        cvv->>cmd: init(request, response)
        activate cmd
        deactivate cmd
        cvv->>cmd: process()
        activate cmd
          ref over cmd #ffffff
            // Session management
            continueBusinessTransaction()
          end ref
          create lm
          cmd->>lm: lock = ReadWriteLockManager.getInstance()
          cmd->>lm: releaseReadAllLock()

            ref over lm
              Release read-all lock
            end ref

          alt Lock released
                  cmd->>uw: getCurrent().commit()
        ref over uw, DBUtil
          UoW commits
        end ref
            cmd->>DBUtil: getConnection().closeConnection()
            activate DBUtil
            deactivate DBUtil
            cvv->>FE: 201 Created
          else SQLException
            cmd->>DBUtil: getConnection().rollback()
            activate DBUtil
            deactivate DBUtil
            cmd->>DBUtil: getConnection().closeConnection()
            activate DBUtil
            deactivate DBUtil
            cmd-->>cvv: SQLException
            cvv-->>FE: 400 Bad Request
          end
        deactivate cmd
      end
    deactivate cvv
  deactivate FE
@enduml