
steps:
  - label: "Check env"
    command: "./check_environment_var.sh"
  
  - label: “Forward to backend folder”
    command: cd event-backend
  
  - label: "Docker Build" 
    plugins:
      - docker-login#v2.2.0:
          username: docerfnc
   
      
      # Resolves to https://github.com/my-org/docker-buildkite-plugin
      - docker-compose#v4.16.0:
          build: -t event-backend .
          image-repository: docerfnc/ticketbooking-a-buildkite-test

  - label: "Docker run"
    plugins:
      - docker-login#v2.2.0:
          username: docerfnc
      - docker-compose#v4.16.0:
	  run: event-backend
