steps:
  - label: “Forward to backend folder”
    command: cd event-backend
  
  - label: "Docker Test" 
    plugins:
      
      # Resolves to https://github.com/my-org/docker-buildkite-plugin
      - docker-compose#v4.16.0:
          login: --username=${DOCKER_USERNAME}
          command: ${DOCKER_PASSWD}
          - wait
          build: .
          image-repository: docerfnc/ticketbooking-a-buildkite-test
          run: .
