steps:
  - label: “Forward to backend folder”
    command: cd event-backend

  
  - label: "Docker Test" 
    plugins:
      
      # Resolves to https://github.com/my-org/docker-buildkite-plugin
      - docker-compose#v4.16.0:
          build: .
          image-repository: docerfnc/ticketbooking-a-buildkite-test
