steps:
  - label: “Forward to backend folder”
    command: cd event-backend
  
  - label: "Docker Test" 
    plugins:
      # - docker#v5.9.0:
      #     login: --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
      
      # Resolves to https://github.com/my-org/docker-buildkite-plugin
      - docker-compose#v4.16.0:
          build: .
          image-repository: docerfnc/ticketbooking-a-buildkite-test
          run: .
